"use client";

import * as React from "react";

export type User = {
  id: string;
  facilityId: string;
  
  // Role & General Details
  role: string;
  employeeId: string;
  username: string;
  fullName: string;
  gender: string;
  
  // Contact Information
  mobileNumber: string;
  email: string;
  address: string;
  pincode: string;
  locality: string;
  block: string;
  district: string;
  state: string;
  
  // Professional Credentials (Doctor only)
  qualification?: string;
  designation?: string;
  registrationNo?: string;
  registrationCouncil?: string;
  hprId?: string;
  
  // Department and Charges
  consultationCharges: number;
  departments?: string[]; // Array of department names
  
  // Metadata
  createdBy: string;
  createdAt: string;
  lastModifiedBy: string;
  lastModifiedAt: string;
};

type UsersContextType = {
  users: User[];
  getUserById: (id: string) => User | undefined;
  addUser: (user: User) => void;
  updateUser: (id: string, user: Partial<User>) => void;
  deleteUser: (id: string) => void;
};

const UsersContext = React.createContext<UsersContextType | undefined>(undefined);

const INITIAL_USERS: User[] = [
  // Facility 1 - Main Hospital
  {
    id: "1",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC001",
    username: "dr.kumar",
    fullName: "Dr. Rajesh Kumar",
    gender: "male",
    mobileNumber: "9988776655",
    email: "rajesh.kumar@hospital.com",
    address: "456 Medical Plaza",
    pincode: "110001",
    locality: "Connaught Place",
    block: "Block D",
    district: "New Delhi",
    state: "Delhi",
    qualification: "MBBS, MS (Ortho)",
    designation: "Orthopedic Surgeon",
    registrationNo: "MCI54321",
    registrationCouncil: "Medical Council of India",
    hprId: "91-1234-5678-9012",
    consultationCharges: 600,
    departments: ["Emergency (ER)"],
    createdBy: "Admin",
    createdAt: "10-JAN-25, 08:30 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "15-FEB-25, 10:00 AM",
  },
  {
    id: "2",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC002",
    username: "dr.smith",
    fullName: "Dr. Sarah Smith",
    gender: "female",
    mobileNumber: "9876543210",
    email: "sarah.smith@hospital.com",
    address: "123 Medical Center Dr",
    pincode: "10001",
    locality: "Manhattan",
    block: "Block B",
    district: "New York",
    state: "Maharashtra",
    qualification: "MBBS, MD (Cardiology)",
    designation: "Senior Cardiologist",
    registrationNo: "MCI12345",
    registrationCouncil: "Medical Council of India",
    hprId: "91-2345-6789-0123",
    consultationCharges: 500,
    departments: ["In-Patient (IPD)", "Laboratory (LAB)"],
    createdBy: "John Doe",
    createdAt: "15-JAN-25, 02:15 PM",
    lastModifiedBy: "Jane Smith",
    lastModifiedAt: "20-FEB-25, 03:30 PM",
  },
  {
    id: "3",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC003",
    username: "dr.sharma",
    fullName: "Dr. Priya Sharma",
    gender: "female",
    mobileNumber: "9123456789",
    email: "priya.sharma@hospital.com",
    address: "789 Healthcare Avenue",
    pincode: "400001",
    locality: "Andheri West",
    block: "Block A",
    district: "Mumbai",
    state: "Maharashtra",
    qualification: "MBBS, MD (Pediatrics)",
    designation: "Pediatrician",
    registrationNo: "MCI23456",
    registrationCouncil: "Medical Council of India",
    hprId: "91-3456-7890-1234",
    consultationCharges: 400,
    departments: ["Pharmacy (PHARM)"],
    createdBy: "Sarah Johnson",
    createdAt: "20-JAN-25, 11:00 AM",
    lastModifiedBy: "Sarah Johnson",
    lastModifiedAt: "25-FEB-25, 04:45 PM",
  },
  {
    id: "4",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC004",
    username: "dr.patel",
    fullName: "Dr. Amit Patel",
    gender: "male",
    mobileNumber: "9876789012",
    email: "amit.patel@hospital.com",
    address: "321 Neurology Center",
    pincode: "560001",
    locality: "MG Road",
    block: "Block C",
    district: "Bangalore",
    state: "Karnataka",
    qualification: "MBBS, DM (Neurology)",
    designation: "Neurologist",
    registrationNo: "MCI34567",
    registrationCouncil: "Medical Council of India",
    hprId: "91-4567-8901-2345",
    consultationCharges: 700,
    departments: ["Emergency (ER)"],
    createdBy: "Admin",
    createdAt: "05-FEB-25, 09:20 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "10-MAR-25, 11:30 AM",
  },
  {
    id: "5",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC005",
    username: "dr.desai",
    fullName: "Dr. Anita Desai",
    gender: "female",
    mobileNumber: "9345678901",
    email: "anita.desai@hospital.com",
    address: "654 Women's Health Center",
    pincode: "380001",
    locality: "Satellite",
    block: "Block E",
    district: "Ahmedabad",
    state: "Gujarat",
    qualification: "MBBS, MS (Gynecology)",
    designation: "Gynecologist",
    registrationNo: "MCI45678",
    registrationCouncil: "Medical Council of India",
    hprId: "91-5678-9012-3456",
    consultationCharges: 450,
    departments: ["In-Patient (IPD)"],
    createdBy: "Admin",
    createdAt: "01-MAR-25, 10:00 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "14-MAR-25, 02:15 PM",
  },
  {
    id: "6",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC006",
    username: "dr.singh",
    fullName: "Dr. Vikram Singh",
    gender: "male",
    mobileNumber: "9234567890",
    email: "vikram.singh@hospital.com",
    address: "987 Surgical Center",
    pincode: "500001",
    locality: "Banjara Hills",
    block: "Block F",
    district: "Hyderabad",
    state: "Telangana",
    qualification: "MBBS, MS (General Surgery)",
    designation: "General Surgeon",
    registrationNo: "MCI56789",
    registrationCouncil: "Medical Council of India",
    hprId: "91-6789-0123-4567",
    consultationCharges: 800,
    departments: ["Laboratory (LAB)"],
    createdBy: "Sarah Johnson",
    createdAt: "10-FEB-25, 03:00 PM",
    lastModifiedBy: "Sarah Johnson",
    lastModifiedAt: "18-MAR-25, 05:20 PM",
  },
  {
    id: "7",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC007",
    username: "dr.reddy",
    fullName: "Dr. Meera Reddy",
    gender: "female",
    mobileNumber: "9456789012",
    email: "meera.reddy@hospital.com",
    address: "741 Skin Care Clinic",
    pincode: "600001",
    locality: "T Nagar",
    block: "Block G",
    district: "Chennai",
    state: "Tamil Nadu",
    qualification: "MBBS, MD (Dermatology)",
    designation: "Dermatologist",
    registrationNo: "MCI67890",
    registrationCouncil: "Medical Council of India",
    hprId: "91-7890-1234-5678",
    consultationCharges: 350,
    departments: ["Pharmacy (PHARM)"],
    createdBy: "John Doe",
    createdAt: "12-FEB-25, 11:45 AM",
    lastModifiedBy: "John Doe",
    lastModifiedAt: "19-MAR-25, 09:10 AM",
  },
  {
    id: "8",
    facilityId: "1",
    role: "DOCTOR",
    employeeId: "DOC008",
    username: "dr.yadav",
    fullName: "Dr. Kaushendra Yadav",
    gender: "male",
    mobileNumber: "9878787676",
    email: "kaushendra.yadav@hospital.com",
    address: "852 General Medicine Wing",
    pincode: "226001",
    locality: "Hazratganj",
    block: "Block H",
    district: "Lucknow",
    state: "Uttar Pradesh",
    qualification: "MBBS, MD (General Medicine)",
    designation: "General Physician",
    registrationNo: "MCI78901",
    registrationCouncil: "Medical Council of India",
    hprId: "91-8777-6798-0979",
    consultationCharges: 300,
    departments: ["Emergency (ER)"],
    createdBy: "Jane Smith",
    createdAt: "18-FEB-25, 02:30 PM",
    lastModifiedBy: "Jane Smith",
    lastModifiedAt: "20-MAR-25, 04:15 PM",
  },
  {
    id: "9",
    facilityId: "1",
    role: "FRONTDESK",
    employeeId: "EMP05811",
    username: "nasir",
    fullName: "M Nasir",
    gender: "male",
    mobileNumber: "9876785087",
    email: "nasir@hospital.com",
    address: "45 Park Avenue",
    pincode: "560001",
    locality: "MG Road",
    block: "Block A",
    district: "Bangalore Urban",
    state: "Karnataka",
    consultationCharges: 0,
    createdBy: "Admin",
    createdAt: "22-FEB-25, 08:00 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "22-MAR-25, 10:30 AM",
  },
  {
    id: "10",
    facilityId: "1",
    role: "NURSE",
    employeeId: "NUR8907",
    username: "mina",
    fullName: "Mina Sharma",
    gender: "female",
    mobileNumber: "7408242287",
    email: "mina.sharma@hospital.com",
    address: "78 Healthcare Lane",
    pincode: "400001",
    locality: "Andheri East",
    block: "Block C",
    district: "Mumbai",
    state: "Maharashtra",
    consultationCharges: 0,
    createdBy: "Sarah Johnson",
    createdAt: "25-FEB-25, 01:15 PM",
    lastModifiedBy: "Sarah Johnson",
    lastModifiedAt: "23-MAR-25, 03:45 PM",
  },
  
  // Facility 2 - East Wing Clinic
  {
    id: "11",
    facilityId: "2",
    role: "DOCTOR",
    employeeId: "DOC101",
    username: "dr.thompson",
    fullName: "Dr. Sarah Thompson",
    gender: "female",
    mobileNumber: "9876543210",
    email: "sarah.thompson@hospital.com",
    address: "101 Medical District",
    pincode: "700001",
    locality: "Park Street",
    block: "Block I",
    district: "Kolkata",
    state: "West Bengal",
    qualification: "MBBS, MD (General Medicine)",
    designation: "General Physician",
    registrationNo: "MCI89012",
    registrationCouncil: "Medical Council of India",
    hprId: "91-1234-5678-9012",
    consultationCharges: 350,
    departments: ["In-Patient (IPD)"],
    createdBy: "Admin",
    createdAt: "03-JAN-25, 09:00 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "12-MAR-25, 11:20 AM",
  },
  {
    id: "12",
    facilityId: "2",
    role: "DOCTOR",
    employeeId: "DOC102",
    username: "dr.chen",
    fullName: "Dr. Michael Chen",
    gender: "male",
    mobileNumber: "9765432109",
    email: "michael.chen@hospital.com",
    address: "202 ENT Specialty Center",
    pincode: "110002",
    locality: "Karol Bagh",
    block: "Block J",
    district: "New Delhi",
    state: "Delhi",
    qualification: "MBBS, MS (ENT)",
    designation: "ENT Specialist",
    registrationNo: "MCI90123",
    registrationCouncil: "Medical Council of India",
    hprId: "91-2345-6789-0123",
    consultationCharges: 400,
    departments: ["Laboratory (LAB)"],
    createdBy: "John Doe",
    createdAt: "08-JAN-25, 10:30 AM",
    lastModifiedBy: "John Doe",
    lastModifiedAt: "15-MAR-25, 02:45 PM",
  },
  {
    id: "13",
    facilityId: "2",
    role: "DOCTOR",
    employeeId: "DOC103",
    username: "dr.nair",
    fullName: "Dr. Kavita Nair",
    gender: "female",
    mobileNumber: "9654321098",
    email: "kavita.nair@hospital.com",
    address: "303 Eye Care Center",
    pincode: "682001",
    locality: "Ernakulam",
    block: "Block K",
    district: "Kochi",
    state: "Kerala",
    qualification: "MBBS, MS (Ophthalmology)",
    designation: "Ophthalmologist",
    registrationNo: "MCI01234",
    registrationCouncil: "Medical Council of India",
    hprId: "91-3456-7890-1234",
    consultationCharges: 450,
    departments: ["Pharmacy (PHARM)"],
    createdBy: "Sarah Johnson",
    createdAt: "14-JAN-25, 02:00 PM",
    lastModifiedBy: "Sarah Johnson",
    lastModifiedAt: "18-MAR-25, 04:30 PM",
  },
  {
    id: "14",
    facilityId: "2",
    role: "NURSE",
    employeeId: "NUR456",
    username: "ppatel",
    fullName: "Priya Patel",
    gender: "female",
    mobileNumber: "9123456789",
    email: "priya.patel@hospital.com",
    address: "78 Healthcare Lane",
    pincode: "400001",
    locality: "Andheri East",
    block: "Block C",
    district: "Mumbai",
    state: "Maharashtra",
    consultationCharges: 0,
    createdBy: "Admin",
    createdAt: "20-JAN-25, 08:45 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "20-MAR-25, 10:15 AM",
  },
  {
    id: "15",
    facilityId: "2",
    role: "FRONTDESK",
    employeeId: "EMP234",
    username: "ravi",
    fullName: "Ravi Kumar",
    gender: "male",
    mobileNumber: "9234567891",
    email: "ravi.kumar@hospital.com",
    address: "45 Reception Area",
    pincode: "110001",
    locality: "Connaught Place",
    block: "Block A",
    district: "New Delhi",
    state: "Delhi",
    consultationCharges: 0,
    createdBy: "John Doe",
    createdAt: "28-JAN-25, 09:30 AM",
    lastModifiedBy: "John Doe",
    lastModifiedAt: "22-MAR-25, 01:00 PM",
  },
  
  // Facility 3 - North Diagnostic Center
  {
    id: "16",
    facilityId: "3",
    role: "DOCTOR",
    employeeId: "DOC201",
    username: "dr.malhotra",
    fullName: "Dr. Arjun Malhotra",
    gender: "male",
    mobileNumber: "9543210987",
    email: "arjun.malhotra@hospital.com",
    address: "404 Radiology Wing",
    pincode: "302001",
    locality: "C Scheme",
    block: "Block L",
    district: "Jaipur",
    state: "Rajasthan",
    qualification: "MBBS, MD (Radiology)",
    designation: "Radiologist",
    registrationNo: "MCI11223",
    registrationCouncil: "Medical Council of India",
    hprId: "91-4567-8901-2345",
    consultationCharges: 500,
    departments: ["Emergency (ER)"],
    createdBy: "Admin",
    createdAt: "05-JAN-25, 11:00 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "16-MAR-25, 03:20 PM",
  },
  {
    id: "17",
    facilityId: "3",
    role: "DOCTOR",
    employeeId: "DOC202",
    username: "dr.verma",
    fullName: "Dr. Sunita Verma",
    gender: "female",
    mobileNumber: "9432109876",
    email: "sunita.verma@hospital.com",
    address: "505 Pathology Lab",
    pincode: "201001",
    locality: "Sector 18",
    block: "Block M",
    district: "Noida",
    state: "Uttar Pradesh",
    qualification: "MBBS, MD (Pathology)",
    designation: "Pathologist",
    registrationNo: "MCI22334",
    registrationCouncil: "Medical Council of India",
    hprId: "91-5678-9012-3456",
    consultationCharges: 400,
    departments: ["Laboratory (LAB)"],
    createdBy: "Sarah Johnson",
    createdAt: "12-JAN-25, 01:30 PM",
    lastModifiedBy: "Sarah Johnson",
    lastModifiedAt: "17-MAR-25, 05:00 PM",
  },
  {
    id: "18",
    facilityId: "3",
    role: "FRONTDESK",
    employeeId: "EMP789",
    username: "jlee",
    fullName: "Jennifer Lee",
    gender: "female",
    mobileNumber: "8765432109",
    email: "jennifer.lee@hospital.com",
    address: "606 Reception Area",
    pincode: "411001",
    locality: "Koregaon Park",
    block: "Block N",
    district: "Pune",
    state: "Maharashtra",
    consultationCharges: 0,
    createdBy: "John Doe",
    createdAt: "19-JAN-25, 08:15 AM",
    lastModifiedBy: "John Doe",
    lastModifiedAt: "19-MAR-25, 12:30 PM",
  },
  {
    id: "19",
    facilityId: "3",
    role: "NURSE",
    employeeId: "NUR567",
    username: "anjali",
    fullName: "Anjali Gupta",
    gender: "female",
    mobileNumber: "9345678902",
    email: "anjali.gupta@hospital.com",
    address: "123 Nursing Wing",
    pincode: "560001",
    locality: "MG Road",
    block: "Block B",
    district: "Bangalore",
    state: "Karnataka",
    consultationCharges: 0,
    createdBy: "Admin",
    createdAt: "26-JAN-25, 10:45 AM",
    lastModifiedBy: "Admin",
    lastModifiedAt: "21-MAR-25, 02:50 PM",
  },
  {
    id: "20",
    facilityId: "3",
    role: "DOCTOR",
    employeeId: "DOC203",
    username: "dr.iyer",
    fullName: "Dr. Ramesh Iyer",
    gender: "male",
    mobileNumber: "9876543211",
    email: "ramesh.iyer@hospital.com",
    address: "707 Diagnostic Center",
    pincode: "600001",
    locality: "T Nagar",
    block: "Block O",
    district: "Chennai",
    state: "Tamil Nadu",
    qualification: "MBBS, MD (Radiology)",
    designation: "Radiologist",
    registrationNo: "MCI33445",
    registrationCouncil: "Medical Council of India",
    hprId: "91-6789-0123-4567",
    consultationCharges: 450,
    departments: ["Laboratory (LAB)"],
    createdBy: "Sarah Johnson",
    createdAt: "02-FEB-25, 03:15 PM",
    lastModifiedBy: "Sarah Johnson",
    lastModifiedAt: "24-MAR-25, 11:40 AM",
  },
];

export function UsersProvider({ children }: { children: React.ReactNode }) {
  const [users, setUsers] = React.useState<User[]>(INITIAL_USERS);

  const getUserById = (id: string) => {
    return users.find((user) => user.id === id);
  };

  const addUser = (user: User) => {
    setUsers((prev) => [...prev, user]);
  };

  const updateUser = (id: string, updatedUser: Partial<User>) => {
    setUsers((prev) =>
      prev.map((user) =>
        user.id === id ? { ...user, ...updatedUser } : user
      )
    );
  };

  const deleteUser = (id: string) => {
    setUsers((prev) => prev.filter((user) => user.id !== id));
  };

  return (
    <UsersContext.Provider
      value={{
        users,
        getUserById,
        addUser,
        updateUser,
        deleteUser,
      }}
    >
      {children}
    </UsersContext.Provider>
  );
}

export function useUsers() {
  const context = React.useContext(UsersContext);
  if (context === undefined) {
    throw new Error("useUsers must be used within a UsersProvider");
  }
  return context;
}